myVariable = 0

def when_started1():
    global myVariable
    drivetrain.drive_for(FORWARD, 500, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 500, MM)
    drivetrain.turn_for(LEFT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 300, MM)
    drivetrain.turn_for(RIGHT, 5, DEGREES)
    drivetrain.drive_for(FORWARD, 350, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 200, MM)
    drivetrain.drive_for(FORWARD, 50, MM)
    drivetrain.turn_for(LEFT, 10, DEGREES)
    drivetrain.drive_for(FORWARD, 50, MM)
    drivetrain.turn_for(RIGHT, 5, DEGREES)
    drivetrain.drive_for(FORWARD, 300, MM)
    drivetrain.turn_for(RIGHT, 45, DEGREES)
    drivetrain.drive_for(REVERSE, 50, MM)
    drivetrain.set_drive_velocity(255, PERCENT)
    drivetrain.drive_for(FORWARD, 400, MM)
    drivetrain.set_drive_velocity(100, PERCENT)
    drivetrain.drive_for(FORWARD, 100, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(FORWARD, 200, MM)
    drivetrain.turn_for(LEFT, 30, DEGREES)
    drivetrain.drive_for(FORWARD, 250, MM)
    drivetrain.drive_for(REVERSE, 75, MM)
    drivetrain.turn_for(RIGHT, 90, DEGREES)
    drivetrain.drive_for(REVERSE, 500, MM)
    drivetrain.drive_for(FORWARD, 100, MM)
    drivetrain.turn_for(RIGHT, 45, DEGREES)
    drivetrain.drive_for(FORWARD, 50, MM)
    drivetrain.turn_for(LEFT, 45, DEGREES)
    drivetrain.drive_for(FORWARD, 2000, MM)

when_started1()
